### ISSUE TITLE
Checkbox not checked

### ISSUE THREAD

**Issue by guilyx** [Stormix/jeveuxsortir#4]
Salut,

Quand je selectionne un motif de déplacement et que je génère l'attestation après l'avoir rempli, la case concernée n'est pas cochée. 

Utilisé ici : https://sortir.wtf

J'utilise Opera.

**Comment by Stormix** [comment]
Salut !
Je te conseille d'utiliser le générateur fournie par le ministère d'intérieur: 
[https://media.interieur.gouv.fr/deplacement-covid-19/](https://media.interieur.gouv.fr/deplacement-covid-19/)
